# Generated by Django 5.0.4 on 2024-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='home',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
